# Generated by Django 3.0.4 on 2020-04-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200414_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
