# Generated by Django 3.0.4 on 2020-04-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_product_product_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_pic',
            field=models.ImageField(blank=True, default='breakfast-1.jpg', null=True, upload_to=''),
        ),
    ]
